# Generated by Django 5.2

from django.db import migrations


def create_departments(apps, schema_editor):
    Department = apps.get_model('phded_app', 'Department')
    for name in ['IT', 'CSE']:
        Department.objects.get_or_create(name=name)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('phded_app', '0002_department_course_content_assignment_question'),
    ]

    operations = [
        migrations.RunPython(create_departments, noop),
    ]
