# Generated by Django 5.2 on 2026-03-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phded_app', '0005_assignment_launched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
