# Generated by Django 5.2 on 2026-03-20 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phded_app', '0006_userprofile_address_userprofile_college'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('twelfth_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attendance_record', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('academic_level', models.CharField(blank=True, choices=[('undergraduate_it', 'Under Graduate - IT'), ('undergraduate_cs', 'Under Graduate - CS'), ('undergraduate_other', 'Under Graduate - Other')], max_length=50)),
                ('course_completion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('study_hours_daily', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gaming_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('social_media_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('extra_curricular_activities', models.CharField(blank=True, max_length=255)),
                ('extra_curricular_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__first_name', 'student__last_name', 'student__email'],
            },
        ),
    ]
