# Generated by Django 5.2 on 2026-03-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phded_app', '0007_studentsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsurvey',
            name='twelfth_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
